
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping Lambda function and dependencies..."
      - zip -r function.zip .
artifacts:
  files:
    - function.zip
